language: node_js
env:
  - BRANCH=beta
  - BRANCH=beta-2
before_script:
  - npm install -g gulp-cli
script: gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: $BRANCH
